name: core
description: "A Flutter project for core functionalities."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Version and build number
version: 1.0.0+1

# Environment constraints
environment:
  sdk: ">=2.17.0 <3.0.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.1.1
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.6
  
  air_buddy:
    path: ../air_buddy
  core_libs:
    path: ../../packages/core_libs
  core_ui:
    path: ../../packages/core_ui

  flutter_riverpod: ^2.5.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.1.4
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  intl: ^0.19.0

# Assets
flutter:
  uses-material-design: true
  assets:
    - assets/icon_svg/
    - assets/animation/

  # Fonts:
  # - family: YourFontFamily
  #   fonts:
  #     - asset: fonts/YourFont-Regular.ttf
  #     - asset: fonts/YourFont-Bold.ttf
